### ISSUE TITLE
invalid json response body

### ISSUE THREAD

**Issue by pcoombe** [SteveCohen/homebridge-BOMgovau#10]
HomeBridge v1.3.4
homebridge-bomgovau v0.1.3

When using the JSON data linked from here http://www.bom.gov.au/products/IDN60901/IDN60901.94763.shtml
> http://www.bom.gov.au/fwo/IDN60901/IDN60901.94763.json

```
[7/21/2021, 8:32:35 PM] [BOM] Current Time is 1626863555065, BOM data expires at 0
[7/21/2021, 8:32:35 PM] [BOM] Updating observations from BOM.
(node:21723) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://www.bom.gov.au/fwo/IDN60901/IDN60901.94763.json reason: Unexpected token < in JSON at position 0
    at /homebridge/node_modules/homebridge-bomgovau/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:21723) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:21723) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://www.bom.gov.au/fwo/IDN60901/IDN60901.94763.json reason: Unexpected token < in JSON at position 0
    at /homebridge/node_modules/homebridge-bomgovau/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:21723) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

about the only thing i can see different is theres no press values at that station. but the JSON seems valid.

**Comment by SteveCohen** [comment]
Yeah. BOM recently implemented a mechanism to prevent screen scraping, which causes this. 

(FWIW: I was surprised that using the JSON file they provide and link to from their website is considered "screen scraping", but after some corro with them questioning this, they confirmed this is indeed their new policy: the JSON file is there but not to be used by machines.)

Fortunately, BOM confirmed their preferred access is using FTP (rather than HTTP as the current plugin) to download XML (rather than JSON) files; or large (~4mb) zip file of observations in JSON format.  So there's a pathway to resolve this... unfortunately that requires some refactoring of the code to use FTP/XML (the 4mb zip file seems... inelegant for regular updates).

PRs very welcome. Otherwise I'll make a big v2 update with this fixed, and some other features at the same time.

**Comment by pcoombe** [comment]
im surprised they even know what screen scraping is, they dont even know what https is. but thanks for the insight.
the canberra one that comes default with the plugin works fine, but to be honest i didnt check anything else, wonder if they are only allowing capital cities or something.

**Comment by pcoombe** [comment]
I think it might be pretty easy to move it over to use request rather than fetch

```
const fetch = require("node-fetch");

let url = "http://www.bom.gov.au/fwo/IDN60901/IDN60901.94763.json";

fetch(url)
    .then(response => {
        response.json().then(json => {

            let obs = json['observations']['header'][0];
            return console.log(obs.name)
        }
        )
    });
```

to 

```
const request = require('request');

let url = "http://www.bom.gov.au/fwo/IDN60901/IDN60901.94763.json";

let options = { json: true };

request(url, options, (error, res, body) => {
    if (error) {
        return console.log(error)
    };

    if (!error && res.statusCode == 200) {
        // do something with JSON, using the 'body' variable
        let obs = body['observations']['header'][0];
        return console.log(obs.name)
    };
});
```

ill see if i can come up with a PR, just need to look into plugin testing in HB.

**Comment by pcoombe** [comment]
OK PR. Was even easier than that, just required a user agent. but fixed some other things as well.
