### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by 9SL9** [SteveCohen/homebridge-BOMgovau#3]
sudo npm install -g homebridge-bomgovau
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-e7bfccc2': Permission denied
npm ERR!

**Comment by SteveCohen** [comment]
This appears to be a permissions problem, so I think this is dependent on your setup, not homebridge-BOMgovau itself. Have you tried without  the `sudo`? Without the `-g`? 

If that doesn't work, there are similar threads and solutions to be found via [google](https://www.google.com/search?q=Command+failed%3A+%2Fusr%2Fbin%2Fgit+submodule+update+-q+--init+--recursive&btnK=Google+Search&oq=Command+failed%3A+%2Fusr%2Fbin%2Fgit+submodule+update+-q+--init+--recursive), but the official doc also has some suggestions: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

Let me know what you try and how it goes?

**Comment by SteveCohen** [comment]
Closing due to no response.
