### ISSUE TITLE
Request ability to disable sensors in config

### ISSUE THREAD

**Issue by danielhelmstedt** [SteveCohen/homebridge-BOMgovau#5]
My local station doesn't have humidity data, so that sensor is sitting useless at 0%. Would love if you could add a "Disable Humidity" etc. flag to the config

**Comment by SteveCohen** [comment]
Hey, have made an initial version and pushed it to a testing branch here: https://github.com/SteveCohen/homebridge-BOMgovau/tree/testing

Install from that source, and add something like this to your accessory config:
```json
...
sensors:{"humidity":false}
...
```
Have also described this in the updated readme.

Please test and let me if it works as expected for you.

**Comment by danielhelmstedt** [comment]
Hey, this worked perfectly for me. Thanks! 😊
