### ISSUE TITLE
Chance of rain or precipitation actuals

### ISSUE THREAD

**Issue by woodgieboodgie** [SteveCohen/homebridge-BOMgovau#9]
Hi Steve,

Great plugin, works without a hitch.  Can a value be pulled from BOM re 'chance of rain'?  Be handy as I want to link my sprinklers to it.

**Comment by SteveCohen** [comment]
Hi - nice idea. The trick will be to find where this data is on the BOM website in machine-readable format. If you could point that out to me I'm happy to consider how to integrate it in the next update (...when I get round to it!)

**Comment by SteveCohen** [comment]
dead thread, closing.

**Comment by sgraystar** [comment]
Hi Steve,
Are you still working on this plugin?
FYI the forecast downloads are available via FTP from http://www.bom.gov.au/catalogue/anon-ftp.shtml
e.g. Canberra is ftp://ftp.bom.gov.au/anon/gen/fwo/IDN10035.xml
